# Generated by Django 3.0.7 on 2020-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simpanan', models.IntegerField(null=True)),
                ('penggunaan', models.CharField(choices=[('Simpanan Jangka Panjang', 'Simpanan Jangka Panjang'), ('Simpanan Jangka Pendek', 'Simpanan Jangka Pendek')], max_length=25, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
